export const ADD_LIST = "ADD_LIST";
export const DELETE_LIST = "DELETE_LIST";
export const INCREASE_QTY = "INCREASE_QTY";
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const GLOBALCART_OPEN = 'GLOBALCART_OPEN';
export const GLOBALCART_CLOSE = 'GLOBALCART_CLOSE';